# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudpush/Tap < Formula
  desc "A cli for managing cloudpush machines."
  homepage "https://portal.cloudpushdev.com/"
  version "0.0.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/cloudpushdev/cli/releases/download/0.0.0/cloudpushdev_Darwin_x86_64.tar.gz"
      sha256 "ea62382c3562b5d93bc0beacdf7f5d10e0856d79b03a170fcd15e1f4930223a4"

      def install
        bin.install "cloudpushdev"
      end
    end
    on_arm do
      url "https://github.com/cloudpushdev/cli/releases/download/0.0.0/cloudpushdev_Darwin_arm64.tar.gz"
      sha256 "960f9381034ea8b6367c07c925cef501afa7ba14556e5e381c6e89fb90812dd9"

      def install
        bin.install "cloudpushdev"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/cli/releases/download/0.0.0/cloudpushdev_Linux_x86_64.tar.gz"
        sha256 "52e5caba50971c7896dff8467d365c6e303f6ae78b9f3e2d5975570218ae9629"

        def install
          bin.install "cloudpushdev"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/cloudpushdev/cli/releases/download/0.0.0/cloudpushdev_Linux_arm64.tar.gz"
        sha256 "1b0234815a6117b20a37b8182e1e7c6ebf4d950bcd383ad5b979061adc8d5cf6"

        def install
          bin.install "cloudpushdev"
        end
      end
    end
  end
end
